mode: 'inference'
use_cuda: 1
num_gpu: 1
sampling_rate: 16000
network: "FRCRN_SE_16K"
checkpoint_dir: "checkpoints/FRCRN_SE_16K"
input_path: ""
output_dir: "outputs/FRCRN_SE_16K"

one_time_decode_length: 60.0
decode_window: 1.0

win_len: 400
win_inc: 100
fft_len: 512
num_mels: 60
win_type: "hamming"
